name: Consolidate Review Comment
description: Consolidates all review results into a single PR comment with dropdowns

inputs:
  review_results:
    description: 'JSON string containing all review results'
    required: true
  github_token:
    description: 'GitHub token for API access'
    required: true

outputs:
  comment_id:
    description: 'ID of the created or updated comment'
    value: ${{ steps.comment.outputs.comment_id }}
  comment_url:
    description: 'URL of the comment'
    value: ${{ steps.comment.outputs.comment_url }}

runs:
  using: composite
  steps:
    - name: Find and update or create comment
      id: comment
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        REVIEW_RESULTS: ${{ inputs.review_results }}
      run: |
        # Constants
        COMMENT_MARKER="<!-- ci-review-comment -->"

        # Parse review results
        echo "$REVIEW_RESULTS" > /tmp/review_results.json

        # Extract individual review data with defaults
        REQUIREMENTS=$(echo "$REVIEW_RESULTS" | jq -r '.requirements // {}')
        RULES=$(echo "$REVIEW_RESULTS" | jq -r '.rules // {}')
        PROJECT_MEMORY=$(echo "$REVIEW_RESULTS" | jq -r '.project_memory // {}')
        AGENTS=$(echo "$REVIEW_RESULTS" | jq -r '.agents // {}')
        SKILLS=$(echo "$REVIEW_RESULTS" | jq -r '.skills // {}')
        UI=$(echo "$REVIEW_RESULTS" | jq -r '.ui // {}')

        # Get commit SHA
        COMMIT_SHA="${{ github.sha }}"
        SHORT_SHA="${COMMIT_SHA:0:7}"

        # Count passed/total reviews
        TOTAL=0
        PASSED=0

        count_review() {
          local review="$1"
          local status=$(echo "$review" | jq -r '.status // "skipped"')
          if [ "$status" != "skipped" ]; then
            TOTAL=$((TOTAL + 1))
            if [ "$status" = "passed" ]; then
              PASSED=$((PASSED + 1))
            fi
          fi
        }

        count_review "$REQUIREMENTS"
        count_review "$RULES"
        count_review "$PROJECT_MEMORY"
        count_review "$AGENTS"
        count_review "$SKILLS"
        count_review "$UI"

        # Helper function to generate status indicator
        get_status_indicator() {
          local status="$1"
          local confidence="$2"

          case "$status" in
            "passed")
              echo "PASSED | Confidence: $confidence"
              ;;
            "failed")
              echo "FAILED | Confidence: $confidence"
              ;;
            "skipped")
              echo "Skipped"
              ;;
            *)
              echo "Unknown"
              ;;
          esac
        }

        # Build the complete comment body
        build_comment_body() {
          cat <<COMMENT
        $COMMENT_MARKER
        ## Code Review Results

        **Commit:** \`$SHORT_SHA\` | **Status:** $PASSED/$TOTAL Passed

        ---

        <details>
        <summary>Requirements Review $(echo "$REQUIREMENTS" | jq -r 'if .status == "passed" then "PASSED" elif .status == "failed" then "FAILED" else "-- Skipped" end')</summary>

        $(echo "$REQUIREMENTS" | jq -r '.summary // "No requirements to verify."')

        </details>

        <details>
        <summary>Rules Review $(echo "$RULES" | jq -r 'if .status == "passed" then "PASSED" elif .status == "failed" then "FAILED" else "-- Skipped" end')</summary>

        $(echo "$RULES" | jq -r '.summary // "No rules to verify."')

        </details>

        <details>
        <summary>Project Memory Review $(echo "$PROJECT_MEMORY" | jq -r 'if .status == "passed" then "PASSED" elif .status == "failed" then "FAILED" else "-- Skipped" end')</summary>

        $(echo "$PROJECT_MEMORY" | jq -r '.summary // "No CLAUDE.md files modified."')

        </details>

        <details>
        <summary>Agents Review $(echo "$AGENTS" | jq -r 'if .status == "passed" then "PASSED" elif .status == "failed" then "FAILED" else "-- Skipped" end')</summary>

        $(echo "$AGENTS" | jq -r '.summary // "No agent files modified."')

        </details>

        <details>
        <summary>Skills Review $(echo "$SKILLS" | jq -r 'if .status == "passed" then "PASSED" elif .status == "failed" then "FAILED" else "-- Skipped" end')</summary>

        $(echo "$SKILLS" | jq -r '.summary // "No skill files modified."')

        </details>

        <details>
        <summary>UI Review $(echo "$UI" | jq -r 'if .status == "passed" then "PASSED" elif .status == "failed" then "FAILED" else "-- Skipped" end')</summary>

        $(echo "$UI" | jq -r '.summary // "No UI files modified."')

        </details>

        ---

        *Automated by Claude Code CI*
        COMMENT
        }

        # Build the comment body
        COMMENT_BODY=$(build_comment_body)

        # Save comment body to file for API call
        echo "$COMMENT_BODY" > /tmp/comment_body.md

        # Get PR number
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          PR_NUMBER="${{ github.event.pull_request.number }}"
        else
          # Try to find PR for this commit
          PR_NUMBER=$(gh pr list --state open --json number,headRefName --jq ".[] | select(.headRefName == \"${{ github.ref_name }}\") | .number" 2>/dev/null || echo "")
        fi

        if [ -z "$PR_NUMBER" ]; then
          echo "No PR found, skipping comment"
          echo "comment_id=" >> $GITHUB_OUTPUT
          echo "comment_url=" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Find existing comment with marker
        EXISTING_COMMENT_ID=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments" \
          --jq ".[] | select(.body | contains(\"$COMMENT_MARKER\")) | .id" \
          2>/dev/null | head -1)

        if [ -n "$EXISTING_COMMENT_ID" ]; then
          # Update existing comment
          RESPONSE=$(gh api \
            --method PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${{ github.repository }}/issues/comments/${EXISTING_COMMENT_ID}" \
            -f body="$(cat /tmp/comment_body.md)")

          COMMENT_ID="$EXISTING_COMMENT_ID"
          COMMENT_URL=$(echo "$RESPONSE" | jq -r '.html_url')
          echo "Updated existing comment: $COMMENT_ID"
        else
          # Create new comment
          RESPONSE=$(gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments" \
            -f body="$(cat /tmp/comment_body.md)")

          COMMENT_ID=$(echo "$RESPONSE" | jq -r '.id')
          COMMENT_URL=$(echo "$RESPONSE" | jq -r '.html_url')
          echo "Created new comment: $COMMENT_ID"
        fi

        echo "comment_id=$COMMENT_ID" >> $GITHUB_OUTPUT
        echo "comment_url=$COMMENT_URL" >> $GITHUB_OUTPUT
